export const PlansData = [
  {
    duration: "1 Months",
    title: "Basic Plan",
    fees:"Free",
    badge: false,
    Free_Public_Profile: true,
    Check_Premium_Profiles: true,
    Public_chat_room_access: true,
    Forum_view_only: true,
    Interact_with_Photos: true,
    Access_to_Public_Chatrooms: true,
    Access_to_1_1_Chat: true,
    Unlimited_Private_Messages: false,
    Unlimited_Forum_Posts: false,
    Private_Galleries: false,
    Friends_Playmates_Only_Gallery: false,
    PPV_Gallery: false,
    Unlimited_Private_Chat_Rooms: false,
    Unlimited_Private_Galleries: false,
    upgrade:false
  },
  {
    duration: "1 Months",
    title: "Premium",
    fees:"£5 /mo",
    badge: true,
    Free_Public_Profile: true,
    Check_Premium_Profiles: true,
    Public_chat_room_access: true,
    Forum_view_only: true,
    Interact_with_Photos: true,
    Access_to_Public_Chatrooms: true,
    Access_to_1_1_Chat: true,
    Unlimited_Private_Messages: true,
    Unlimited_Forum_Posts: true,
    Private_Galleries: true,
    Friends_Playmates_Only_Gallery: true,
    PPV_Gallery: true,
    Unlimited_Private_Chat_Rooms: true,
    Unlimited_Private_Galleries: true,
    upgrade:true
  },
  {
    duration: "3 Months",
    title: "Basic Plan",
    fees:"Free",
    badge: false,
    Free_Public_Profile: true,
    Check_Premium_Profiles: true,
    Public_chat_room_access: true,
    Forum_view_only: true,
    Interact_with_Photos: true,
    Access_to_Public_Chatrooms: true,
    Access_to_1_1_Chat: true,
    Unlimited_Private_Messages: false,
    Unlimited_Forum_Posts: false,
    Private_Galleries: false,
    Friends_Playmates_Only_Gallery: false,
    PPV_Gallery: false,
    Unlimited_Private_Chat_Rooms: false,
    Unlimited_Private_Galleries: false,
    upgrade:false
  },
  {
    duration: "3 Months",
    title: "Premium",
    fees:"£15 /mo",
    badge: true,
    Free_Public_Profile: true,
    Check_Premium_Profiles: true,
    Public_chat_room_access: true,
    Forum_view_only: true,
    Interact_with_Photos: true,
    Access_to_Public_Chatrooms: true,
    Access_to_1_1_Chat: true,
    Unlimited_Private_Messages: true,
    Unlimited_Forum_Posts: true,
    Private_Galleries: true,
    Friends_Playmates_Only_Gallery: true,
    PPV_Gallery: true,
    Unlimited_Private_Chat_Rooms: true,
    Unlimited_Private_Galleries: true,
    upgrade:true
  },
  {
    duration: "12 Months",
    title: "Basic Plan",
    fees:"Free",
    badge: false,
    Free_Public_Profile: true,
    Check_Premium_Profiles: true,
    Public_chat_room_access: true,
    Forum_view_only: true,
    Interact_with_Photos: true,
    Access_to_Public_Chatrooms: true,
    Access_to_1_1_Chat: true,
    Unlimited_Private_Messages: false,
    Unlimited_Forum_Posts: false,
    Private_Galleries: false,
    Friends_Playmates_Only_Gallery: false,
    PPV_Gallery: false,
    Unlimited_Private_Chat_Rooms: false,
    Unlimited_Private_Galleries: false,
    upgrade:false
  },
  {
    duration: "12 Months",
    title: "Premium",
    fees:"£25 /mo",
    badge: true,
    Free_Public_Profile: true,
    Check_Premium_Profiles: true,
    Public_chat_room_access: true,
    Forum_view_only: true,
    Interact_with_Photos: true,
    Access_to_Public_Chatrooms: true,
    Access_to_1_1_Chat: true,
    Unlimited_Private_Messages: true,
    Unlimited_Forum_Posts: true,
    Private_Galleries: true,
    Friends_Playmates_Only_Gallery: true,
    PPV_Gallery: true,
    Unlimited_Private_Chat_Rooms: true,
    Unlimited_Private_Galleries: true,
    upgrade:true
  },
];
